### ISSUE TITLE
Cursor behavior while dragging in Safari 8

### ISSUE THREAD

**Issue by ctlusto** [desmosinc/scrubber#12]
In Safari 8, a hovered `.thumb` displays `cursor: pointer`, like you would expect, but once you start dragging it switches to `cursor: text`.  It just looks weird.  When I'm dragging a UI element, I don't want my cursor to imply I should be highlighting something.

Only an issue in Safari, and it may only be an issue in the latest release, but I'm not sure.  I'm mainly bringing this up because it also affects the sliders in the Desmos app.

Does Safari have an idiosyncratic problem with the selector in here?

``` css
.scrubber .thumb:hover,
.scrubber-vert .thumb:hover,
.thumb.dragging {
  border-width: 0px;
  opacity: 1;
}
```

Does it need to be:

``` css
.scrubber .thumb.dragging {...}

```

for some reason?
